server.port=8080
spring.datasource.url=jdbc:h2:mem:devopsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# CONFIGURACION DE OBSERVABILIDAD

management.endpoints.web.exposure.include=health,info,metrics,prometheus
# Habilitar metricas detalladas usando la sintaxis moderna de Spring Boot 3.x
management.observations.key-values.http.server.requests=true

management.endpoint.health.show-details=always

